<?php

namespace App\Controllers\Admin;

use App\Models\AdminUserModel;
use Core\Controller;

abstract class AdminController extends Controller
{
    public function __construct()
    {
        parent::__construct('Admin');
        if (!isset($_SESSION['admin_id'])) {
            header('Location: /admin/login');
            exit;
        }
    }
    abstract function index();
    public function render($page, $data = []): void
    {
        $_SESSION['permissions'] = (new AdminUserModel())->getPermissionByAdminId($_SESSION['admin_id']);
        $data['admin'] = $_SESSION;
        parent::render($page, $data); // TODO: Change the autogenerated stub
    }
}